services:
  postgres:
    image: postgres:16-alpine
    container_name: clinic_postgres
    restart: always
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic_dev_2569
      POSTGRES_DB: clinic
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    ports:
      - "5433:5432"
    volumes:
      - clinic_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic -d clinic"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: clinic_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  clinic_pgdata:
    name: clinic_pgdata
